<#
.SYNOPSIS
    Installs the myhooks fat jar as the pre-commit git hook.

.DESCRIPTION
    Writes the hook as a POSIX sh script (Git for Windows runs hooks with its
    bundled sh) using LF line endings and UTF-8 without a BOM, so the shebang
    stays valid. When Git's sh.exe can be located, the hook is also chmod +x'd
    so the MSYS executable bit is set.

    Re-running is safe. The first time a hook is installed, any pre-existing
    hook is copied to <hook>.myhooks-backup; scripts/deactivate-hooks.ps1
    restores it.

    Commit messages are no longer checked by myhooks; use the pre-commit
    framework with the gitlint hook (see .pre-commit-config.yaml and .gitlint).
    A commit-msg hook installed by an older myhooks version is retired here so
    that an upgraded jar cannot break `git commit`.

.PARAMETER TargetRepo
    Repository whose .git\hooks directory receives the hooks. Defaults to the
    current directory.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\install-hooks.ps1 C:\src\MyReports
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$TargetRepo = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
    [Console]::Error.WriteLine($Message)
    exit 1
}

$ProjectDir = Split-Path -Parent $PSScriptRoot
$Jar = Join-Path $ProjectDir 'target\myhooks-1.0.0.jar'
$Marker = '# myhooks-hook: generated by myhooks -- do not edit'

if (-not (Test-Path -LiteralPath $Jar -PathType Leaf)) {
    Fail "error: $Jar not found; run 'mvn package' first"
}

$HooksDir = Join-Path $TargetRepo '.git\hooks'
if (-not (Test-Path -LiteralPath $HooksDir -PathType Container)) {
    Fail "error: $HooksDir not found; is $TargetRepo a git repository?"
}

# The hook body is a POSIX sh script; forward slashes avoid backslash surprises
# when it is parsed by Git for Windows' sh.
$JarForHook = $Jar -replace '\\', '/'

function Backup-Hook([string]$Name) {
    $path = Join-Path $HooksDir $Name
    $backup = "${path}.myhooks-backup"
    if ((Test-Path -LiteralPath $path -PathType Leaf) -and
        -not (Select-String -LiteralPath $path -Pattern 'myhooks-hook:' -Quiet) -and
        -not (Test-Path -LiteralPath $backup)) {
        Copy-Item -LiteralPath $path -Destination $backup
        Write-Host "backed up existing $Name to ${Name}.myhooks-backup"
    }
}

function Write-Hook([string]$Name, [string]$Body) {
    $path = Join-Path $HooksDir $Name
    $text = "#!/bin/sh`n$Marker`n$Body`n"
    [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false))
}

# Git's sh lives next to git.exe in a typical Git for Windows install; it is not
# always on PATH in PowerShell.
function Find-Sh {
    $sh = Get-Command 'sh.exe' -ErrorAction SilentlyContinue
    if ($sh) {
        return $sh.Source
    }
    $git = Get-Command 'git.exe' -ErrorAction SilentlyContinue
    if (-not $git) {
        return $null
    }
    $gitDir = Split-Path -Parent $git.Source
    foreach ($candidate in @(
            (Join-Path $gitDir '..\usr\bin\sh.exe'),
            (Join-Path $gitDir '..\bin\sh.exe'))) {
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
    }
    return $null
}

# Best-effort: set the MSYS executable bit so git never ignores the hook.
function Set-HookExecutable {
    $sh = Find-Sh
    if (-not $sh) {
        return
    }
    $quoted = foreach ($name in @('pre-commit', 'commit-msg')) {
        $hookPath = (Join-Path $HooksDir $name) -replace '\\', '/'
        "'" + $hookPath.Replace("'", "'\''") + "'"
    }
    try {
        & $sh -c "chmod +x $($quoted -join ' ')" 2>$null | Out-Null
    } catch {
        # best-effort; git-for-windows usually runs sh hooks regardless
    }
}

# Older myhooks releases installed a commit-msg hook that ran the now-removed
# `myhooks commitmsg` step; leaving it behind would make every commit fail with
# an unknown-argument error. Only a hook carrying the myhooks marker is touched.
function Retire-LegacyCommitMsg {
    $path = Join-Path $HooksDir 'commit-msg'
    $bak = "${path}.myhooks-backup"
    if (-not (Test-Path -LiteralPath $path -PathType Leaf) -or
        -not (Select-String -LiteralPath $path -Pattern 'myhooks-hook:' -Quiet)) {
        return
    }
    Remove-Item -LiteralPath $path -Force
    if (Test-Path -LiteralPath $bak -PathType Leaf) {
        Move-Item -LiteralPath $bak -Destination $path
        Write-Host 'restored previous commit-msg hook'
    } else {
        Write-Host 'removed stale myhooks commit-msg hook (commit messages are now checked by gitlint)'
    }
}

Backup-Hook 'pre-commit'
Retire-LegacyCommitMsg

Write-Hook 'pre-commit' "exec java -jar `"$JarForHook`" `"`$@`""

Set-HookExecutable

Write-Host "installed pre-commit hook in $HooksDir"
