#!/bin/sh
# Installs the myhooks fat jar as the pre-commit and commit-msg git hooks.
#
# Usage: scripts/install-hooks.sh [target-repo]
#   target-repo defaults to the current directory.
#
# Re-running is safe. The first time a hook is installed, any pre-existing hook
# is copied to <hook>.myhooks-backup; scripts/deactivate-hooks.sh restores it.
set -eu

PROJECT_DIR=$(cd "$(dirname "$0")/.." && pwd)
JAR="$PROJECT_DIR/target/myhooks-1.0.0.jar"
TARGET="${1:-$(pwd)}"
MARKER="# myhooks-hook: generated by myhooks -- do not edit"

if [ ! -f "$JAR" ]; then
    echo "error: $JAR not found; run 'mvn package' first" >&2
    exit 1
fi

HOOKS_DIR="$TARGET/.git/hooks"
if [ ! -d "$HOOKS_DIR" ]; then
    echo "error: $HOOKS_DIR not found; is $TARGET a git repository?" >&2
    exit 1
fi

# Preserve a user's own hook the first time we take over the name.
backup() {
    hook="$1"
    path="$HOOKS_DIR/$hook"
    if [ -f "$path" ] && ! grep -q "myhooks-hook:" "$path" 2>/dev/null \
            && [ ! -f "$path.myhooks-backup" ]; then
        cp "$path" "$path.myhooks-backup"
        echo "backed up existing $hook to $hook.myhooks-backup"
    fi
}

backup pre-commit
backup commit-msg

cat > "$HOOKS_DIR/pre-commit" <<EOF
#!/bin/sh
$MARKER
exec java -jar "$JAR" "\$@"
EOF
chmod +x "$HOOKS_DIR/pre-commit"

cat > "$HOOKS_DIR/commit-msg" <<EOF
#!/bin/sh
$MARKER
exec java -jar "$JAR" commitmsg "\$1"
EOF
chmod +x "$HOOKS_DIR/commit-msg"

echo "installed pre-commit and commit-msg hooks in $HOOKS_DIR"
